spring.application.name=wealth-management


# ==========================
# Database Configuration
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/wealth_db
spring.datasource.username=postgres
spring.datasource.password=552283
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Run data.sql after Hibernate creates/updates tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server Port
server.port=8081

# ==========================
# Logging Configuration
# ==========================
logging.level.org.springframework.web=DEBUG
logging.level.com.wealth=DEBUG

# Disable Spring Boot banner
spring.main.banner-mode=off
